### ISSUE TITLE
More structure format for date details

### ISSUE THREAD

**Issue by mwkaufman** [rearc-data/nyt-states-reopen-status-covid-19#1]
Is it possible to provide a more structured format to the date details? Specifically, have a clear date field and level of food and drink reopening?

**Comment by derekwolpert** [comment]
@milin82 @mwkaufman Opened a new branch which parses out date values into separate fields, and breaks down categories of "reopened" and "reopening_soon" resources/business types into separate fields.

https://github.com/rearc-data/nyt-states-reopen-status-covid-19/tree/dw/open-status-refactor

**Comment by milin82** [comment]
lgtm
