### ISSUE TITLE
Reopening Feild Not Updating

### ISSUE THREAD

**Issue by brendenenen** [rearc-data/nyt-states-reopen-status-covid-19#6]
Per the NYT article, Michigan is now 'Reopened.' Yet in the pulled data, Michigan is still 'Reopening June 22'. It's been a couple of days since the update on NYT. Is this dataset in AWS Data exchange still being updated?

**Comment by nfunke** [comment]
> Per the NYT article, Michigan is now 'Reopened.' Yet in the pulled data, Michigan is still 'Reopening June 22'. It's been a couple of days since the update on NYT. Is this dataset in AWS Data exchange still being updated?

I just reloaded the data in AWS data exchange and checked that Michigan is now on reopened. You should be good to go, let me know if still see an issue
